config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'

  resources :posts do
    resources :comments
  end
  
  resources :users

  get '/signin', to: 'users#signin_prompt'
  post '/signin', to: 'users#signin'
  get '/signout', to: 'users#signout'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_secure_password

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  enum role: [:user, :author, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_post_id

  # do you need all 7 actions for comments?
  def index
    redirect_to posts_path
  end

  def new
    @comment = Comment.new
  end

  def create

    @comment = @post.comments.create!(comment_params.merge({user_id: session[:user]["id"]}))
    # there's nothing wrong with your approach to associating users and comments
    # but here's another way I think think may be more readable:

    # @user = User.find(session[:user][:id]])
    # @user.comments.create!(comment_params)

    # if we have a method `current_user`, we can eliminate the first line and just
    # do the following:
    # current_user.comments.create!(comment_params)


    redirect_to post_path(@post)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end


  private

  def get_post_id
    @post = Post.find(params[:post_id])
  end


  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create!(post_params.merge({user_id: session[:user]["id"]}))
    # see my note in comments controller... same technique applies here!
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :photo_url, :body)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.all
    @posts = Post.all
    @user_posts = @user.posts.all
  end

  # while this works, and is clever, I found it a bit confusing from a UX perspective...
  # I couldn't find a signup page, and was confused that I could just create a user
  # by 'signing in'... maybe at least indicate as much on the sign in page?
  def signin
    if params[:username].strip == ""
      message = "You forgot to enter a username!"
    elsif params[:password].strip == ""
      message = "You forgot to enter a password!"
    else
      # if username does not exist, create a new user
      if !User.find_by(username: params[:username])
        if User.create(
          username: params[:username],
          password_digest: BCrypt::Password.create(params[:password])
        )
          message = "Your account has been created and you're signed in!"
          sign_in
        else
          # ask if this message is useless in this particular context - will either create user or say wrong password
          message = "Your account couldn't be created. Did you enter a unique username and password?"
        end
      else
        # check password
        decoded_hash = BCrypt::Password.new(User.find_by(username: params[:username]).password_digest)
        if decoded_hash.is_password?(params[:password]) == false
          message = "Your password's wrong!"
          redirect_to :back
        else
          message = "You're signed in, #{params[:username]}! :)"
          sign_in
        end
      end
    end
    puts "-" * 50
    flash[:sign_in_message] = message

  end

  def signin_prompt

  end

  def signout
    reset_session
    redirect_to root_url
  end

  private

  # nice use of a method to extract commonality
  def sign_in
    cookies[:username] = {
      value: params[:username],
      expires: 100.years.from_now
    }
    session[:is_signed_in] = true
    session[:user] = User.find_by(username: params[:username])
    redirect_to posts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= render "form" %>

<%= form_for [@post, @comment], method: :delete do |f| %>
  <%= f.submit "Delete this comment" %>
<% end %>

app/views/comments/new.html.erb
<h2>Add Comment</h2>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribblr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1><%= link_to "Scribblr", posts_path %></h1>
    <nav>

      <%= link_to "Home", posts_path, class: "nav_link" %>
      <%= link_to "New Post", new_post_path, class: "nav_link" %>
      <% if session[:is_signed_in] %>
        <%= link_to "Your Profile", user_path(session[:user]["id"]), class: "nav_link" %>
      <% end %>
      <% if session[:is_signed_in] %>
        <%= link_to "Sign Out: #{session[:user]["username"]}", signout_path, class: "nav_link" %>
      <% else %>
        <%= link_to "Sign In", signin_path, class: "nav_link" %>
      <% end %>
    </nav>
  </header>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :photo_url %>
  <%= f.text_field :photo_url %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<div class="post_form" >

  <h2>Edit Post</h2>

  <%= render "form" %>

  <%= form_for @post, method: :delete do |f| %>
    <%= f.submit "Delete Post" %>
  <% end %>

</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_container">

    <div class="post_header">
      <h2><%= link_to post.title, post %></h2>
      <span class="byline">Posted by <%= post.user.username %> <span><%= time_ago_in_words(post.created_at) %></span> ago</span>
    </div>
      <%= image_tag post.photo_url, class: "post_image" %>
    <div class="post_body">
      <p><%= post.body %></p>
    </div>
    <div class="index_spacer">
    </div>

  </div>
<% end %>

app/views/posts/new.html.erb
<div class="post_form" >
  
  <h2>New Post</h2>

  <%= render "form" %>

</div>

app/views/posts/show.html.erb
<div class="post_container">

  <div class="post_header">
    <h2><%= @post.title %></h2>
    <p class="byline">Posted by <%= @post.user.username %> <span><%= time_ago_in_words(@post.created_at) %></span> ago - <%= link_to "Edit Post", edit_post_path %></p>
  </div>
  <%= image_tag @post.photo_url, class: "post_image" %>
  <div class="post_body">
    <%= @post.body %>
  </div>

</div>
<div class="comment_container">
  <div class="comment_list">
    <ul>
      <% @comments.each do |comment| %>

          <li>
            <%= link_to comment.user.username, user_path(comment.user.id) %>: <%= comment.body %> <span class="comment_timestamp"><%= time_ago_in_words(comment.created_at) %> ago</span>
            <%= link_to "Edit Comment", edit_post_comment_path(@post, comment), class: "edit_link" %>
          </li>

      <% end %>
    </ul>
  </div>

  <!-- could you use the comment form partial here? -->
  <div class="comment_form">
    <%= form_for [@post, Comment.new] do |f| %>
      <%= f.label :body, "New Comment" %>
      <%= f.text_area :body %>

      <%= f.submit %>
    <% end %>
  </div>
</div> <!-- end of comment container div -->

<!-- <%= link_to "Add Comment", new_post_comment_path(@post) %> -->

app/views/users/index.html.erb
<h2>List of Users</h2>

<% @users.each do |user| %>
  <ul>
    <li>
      <%= link_to user.username, user %>
    </li>
  </ul>
<% end %>

app/views/users/show.html.erb
<div class="profile_container">
  <div class="profile_info">
    <%= image_tag @user.photo_url, class: "profile_image", size: "200x200" %>
    <h2><%= @user.username %>'s Profile </h2>
    <p>From: <span class="profile_text"><%= @user.location %></span></p>
    <p>Joined on: <span class="profile_text"><%= @user.created_at.strftime("%b %d, %Y") %></span></p>
    <p>User Type: <span class="profile_text"><%= @user.role %></span></p>
  </div>

  <% if @user_posts.empty? %>
    <p></p>
  <% else %>
    <div class="profile_posts">
      <p>Posts:</p>
      <% @user_posts.each do |post| %>
        <ul>
          <li>
            <%= link_to post.title, post %>
          </li>
        </ul>
      <% end %>
    </div>
  <% end %>

  <% if @comments.empty? %>
    <p></p>
  <% else %>
    <div class="profile_comments">
      <p>Comments:</p>
      <% @comments.each do |comment| %>
        <ul>
          <li>
            "<%= comment.body %>" on <%= link_to @posts.find(comment.post).title, post_path(@posts.find(comment.post)) %>
          </li>
        </ul>
      <% end %>
    </div>
  <% end %>  

</div>

app/views/users/signin_prompt.html.erb
<h2><%= flash[:sign_in_message] %></h2>

<%= form_tag("/signin", method: "post") do %>
  <input type="text" name="username" placeholder="username" value="<%= cookies[:username] %>"/>
  <input type="password" name="password" placeholder="password" />
  <input type="submit" value="Sign in" />
<% end %>